// HamzaPhone Canonical Permissions Registry & Domain Grouping
// Authoritative directory of all resource × action permissions

import type { PermissionItem, PermissionDomain } from '@/types/staff-rbac.types';

export const PERMISSION_DOMAINS: Array<{ id: PermissionDomain; labelFr: string; descriptionFr: string }> = [
  { id: 'CATALOG', labelFr: 'Catalogue & Pièces Détachées', descriptionFr: 'Création, modification et suppression des fiches articles et compatibilités' },
  { id: 'PRICING', labelFr: 'Tarification & Marges', descriptionFr: 'Gestion des prix publics, tarifs grossistes B2B et ajustements en masse' },
  { id: 'INVENTORY', labelFr: 'Stock & Entrepôt Belfort', descriptionFr: 'Réceptions fournisseurs, ajustements d’inventaire et comptabilité' },
  { id: 'ORDERS', labelFr: 'Commandes & Facturation', descriptionFr: 'Validation, avancement des états, annulations et remboursements' },
  { id: 'PAYMENTS', labelFr: 'Paiements & Rapprochement COD', descriptionFr: 'Suivi des encaissements espèces, versements livreurs et rapprochement bancaire' },
  { id: 'DELIVERY', labelFr: 'Livraison & Expéditions EcoTrack', descriptionFr: 'Création des bordereaux transporteur et gestion de la grille 58 Wilayas' },
  { id: 'CUSTOMERS_B2B', labelFr: 'Clients & Grossistes B2B', descriptionFr: 'Validation des dossiers professionnels, RC/NIF et plafonds de crédit' },
  { id: 'SUPPLIERS', labelFr: 'Fournisseurs & Import Direct', descriptionFr: 'Gestion des usines Chine/Local, délais et devises USD/DZD' },
  { id: 'IMPORTS_EXPORTS', labelFr: 'Import / Export & Lots', descriptionFr: 'Téléversement de catalogues 4000+ lignes et exports de classeurs' },
  { id: 'CMS', labelFr: 'Contenu Vitrine & CMS', descriptionFr: 'Gestion des bannières d’accueil, bannières d’annonces et sections réassurance' },
  { id: 'NOTIFICATIONS', labelFr: 'Notifications & Modèles', descriptionFr: 'Hub de notifications, modèles SMS/WhatsApp et passerelles d’alerte' },
  { id: 'ANALYTICS_REPORTS', labelFr: 'Statistiques & Rapports BI', descriptionFr: 'Chiffre d’affaires, rentabilité, conversion, analyse des stocks et exports de rapports' },
  { id: 'ADMIN_SECURITY', labelFr: 'Utilisateurs Staff & Sécurité', descriptionFr: 'Gestion des membres d’équipe, rôles et journal d’audit immuable' },
  { id: 'SYSTEM_SETTINGS', labelFr: 'Paramètres & Configuration', descriptionFr: 'Configuration générale du site, coordonnées et clés API' },
];

export const SYSTEM_PERMISSIONS: PermissionItem[] = [
  // Superuser
  {
    code: 'all',
    resource: 'system',
    action: 'all',
    labelFr: 'Accès Superadmin Absolu (Wildcard)',
    descriptionFr: 'Contourne toutes les restrictions de sécurité pour le compte Propriétaire (OWNER).',
    domain: 'ADMIN_SECURITY',
  },

  // CATALOG
  {
    code: 'products.read',
    resource: 'products',
    action: 'read',
    labelFr: 'Consulter les pièces du catalogue',
    descriptionFr: 'Lecture des fiches produits, références OEM et compatibilités modèles.',
    domain: 'CATALOG',
  },
  {
    code: 'products.create',
    resource: 'products',
    action: 'create',
    labelFr: 'Créer de nouvelles pièces',
    descriptionFr: 'Ajout de nouveaux articles dans la base de données.',
    domain: 'CATALOG',
  },
  {
    code: 'products.update',
    resource: 'products',
    action: 'update',
    labelFr: 'Modifier les pièces existantes',
    descriptionFr: 'Édition des désignations, photos, compatibilités et spécifications.',
    domain: 'CATALOG',
  },
  {
    code: 'products.delete',
    resource: 'products',
    action: 'delete',
    labelFr: 'Supprimer / Archiver des pièces',
    descriptionFr: 'Mise à la corbeille ou archivage définitif d’articles.',
    domain: 'CATALOG',
  },
  {
    code: 'products.bulk_update',
    resource: 'products',
    action: 'bulk_update',
    labelFr: 'Modifications en lot sur le catalogue',
    descriptionFr: 'Changement groupé de statut, marque ou catégorie.',
    domain: 'CATALOG',
  },
  {
    code: 'categories.manage',
    resource: 'categories',
    action: 'manage',
    labelFr: 'Gérer les catégories & arborescence',
    descriptionFr: 'Création et ordonnancement des rayons et familles.',
    domain: 'CATALOG',
  },
  {
    code: 'brands.manage',
    resource: 'brands',
    action: 'manage',
    labelFr: 'Gérer les marques & modèles de téléphones',
    descriptionFr: 'Ajout de marques (Samsung, Apple, Xiaomi) et modèles compatibles.',
    domain: 'CATALOG',
  },

  // PRICING
  {
    code: 'pricing.read',
    resource: 'pricing',
    action: 'read',
    labelFr: 'Consulter les prix d’achat & marges brutes',
    descriptionFr: 'Accès aux données confidentielles de coût d’acquisition fournisseur.',
    domain: 'PRICING',
  },
  {
    code: 'pricing.update',
    resource: 'pricing',
    action: 'update',
    labelFr: 'Modifier les prix unitaires (B2C / B2B)',
    descriptionFr: 'Modification des tarifs de vente public et remises de base.',
    domain: 'PRICING',
  },
  {
    code: 'pricing.bulk_percentage',
    resource: 'pricing',
    action: 'bulk_percentage',
    labelFr: 'Ajustement de prix en pourcentage (%)',
    descriptionFr: 'Hausse ou baisse générale par marque, catégorie ou fournisseur.',
    domain: 'PRICING',
  },
  {
    code: 'pricing.b2b_tiers',
    resource: 'pricing',
    action: 'b2b_tiers',
    labelFr: 'Gérer les paliers grossistes B2B',
    descriptionFr: 'Configuration des remises par palier de volume.',
    domain: 'PRICING',
  },
  {
    code: 'pricing.customer_override',
    resource: 'pricing',
    action: 'customer_override',
    labelFr: 'Prix personnalisés par contrat client',
    descriptionFr: 'Fixation de tarifs dérogatoires négociés pour un atelier spécifique.',
    domain: 'PRICING',
  },

  // INVENTORY
  {
    code: 'inventory.read',
    resource: 'inventory',
    action: 'read',
    labelFr: 'Consulter les stocks physiques & réservations',
    descriptionFr: 'Vue d’ensemble des quantités disponibles et en commande.',
    domain: 'INVENTORY',
  },
  {
    code: 'inventory.adjust',
    resource: 'inventory',
    action: 'adjust',
    labelFr: 'Ajuster les stocks physiques (Inventaire)',
    descriptionFr: 'Écritures manuelles d’ajustement et mise au rebut de casse.',
    domain: 'INVENTORY',
  },
  {
    code: 'inventory.receive',
    resource: 'inventory',
    action: 'receive',
    labelFr: 'Réceptionner les arrivages fournisseurs',
    descriptionFr: 'Enregistrement de bons de réception et entrée en stock.',
    domain: 'INVENTORY',
  },

  // ORDERS
  {
    code: 'orders.read',
    resource: 'orders',
    action: 'read',
    labelFr: 'Consulter toutes les commandes clients & B2B',
    descriptionFr: 'Accès aux détails de facturation, adresses et historiques.',
    domain: 'ORDERS',
  },
  {
    code: 'orders.create',
    resource: 'orders',
    action: 'create',
    labelFr: 'Créer des commandes manuelles',
    descriptionFr: 'Saisie de commandes directes en magasin ou par téléphone.',
    domain: 'ORDERS',
  },
  {
    code: 'orders.update',
    resource: 'orders',
    action: 'update',
    labelFr: 'Modifier et avancer le statut de commande',
    descriptionFr: 'Validation d’appel, passage en préparation atelier.',
    domain: 'ORDERS',
  },
  {
    code: 'orders.cancel',
    resource: 'orders',
    action: 'cancel',
    labelFr: 'Annuler des commandes & libérer le stock',
    descriptionFr: 'Annulation avant expédition avec restitution de la réservation.',
    domain: 'ORDERS',
  },
  {
    code: 'orders.refund',
    resource: 'orders',
    action: 'refund',
    labelFr: 'Émettre des remboursements & avoirs SAV',
    descriptionFr: 'Traitement des réclamations financières et retours.',
    domain: 'ORDERS',
  },

  // PAYMENTS
  {
    code: 'payments.read',
    resource: 'payments',
    action: 'read',
    labelFr: 'Consulter les encaissements & statuts COD',
    descriptionFr: 'Lecture des échéanciers de paiement et soldes attendus.',
    domain: 'PAYMENTS',
  },
  {
    code: 'payments.manage',
    resource: 'payments',
    action: 'manage',
    labelFr: 'Enregistrer encaissements & versements livreur',
    descriptionFr: 'Saisie de l’argent collecté et des versements transporteur.',
    domain: 'PAYMENTS',
  },
  {
    code: 'payments.reconcile',
    resource: 'payments',
    action: 'reconcile',
    labelFr: 'Rapprocher les bordereaux financiers en banque',
    descriptionFr: 'Validation des versements et clôture des bordereaux de réconciliation.',
    domain: 'PAYMENTS',
  },
  {
    code: 'payments.adjust',
    resource: 'payments',
    action: 'adjust',
    labelFr: 'Effectuer des ajustements financiers & régularisations',
    descriptionFr: 'Traitement des écarts, litiges et régularisations manuelles.',
    domain: 'PAYMENTS',
  },

  // DELIVERY
  {
    code: 'delivery.dispatch',
    resource: 'delivery',
    action: 'dispatch',
    labelFr: 'Expédier et générer bordereaux EcoTrack',
    descriptionFr: 'Création d’étiquettes et transfert vers le transporteur.',
    domain: 'DELIVERY',
  },
  {
    code: 'delivery.manage_rates',
    resource: 'delivery',
    action: 'manage_rates',
    labelFr: 'Gérer la grille tarifaire 58 Wilayas',
    descriptionFr: 'Modification des tarifs de livraison à domicile et en stopdesk.',
    domain: 'DELIVERY',
  },

  // CUSTOMERS_B2B
  {
    code: 'customers.read',
    resource: 'customers',
    action: 'read',
    labelFr: 'Consulter le répertoire des clients B2C',
    descriptionFr: 'Lecture des coordonnées et statistiques d’achat.',
    domain: 'CUSTOMERS_B2B',
  },
  {
    code: 'customers.update',
    resource: 'customers',
    action: 'update',
    labelFr: 'Modifier les profils clients B2C',
    descriptionFr: 'Correction d’adresses ou blocage de compte frauduleux.',
    domain: 'CUSTOMERS_B2B',
  },
  {
    code: 'b2b.read',
    resource: 'b2b',
    action: 'read',
    labelFr: 'Consulter les dossiers professionnels B2B',
    descriptionFr: 'Accès aux documents fiscaux (RC, NIF, NIS, AI).',
    domain: 'CUSTOMERS_B2B',
  },
  {
    code: 'b2b.approve',
    resource: 'b2b',
    action: 'approve',
    labelFr: 'Valider / Refuser les candidatures B2B',
    descriptionFr: 'Approbation des comptes réparateurs et revendeurs.',
    domain: 'CUSTOMERS_B2B',
  },
  {
    code: 'b2b.manage_pricing',
    resource: 'b2b',
    action: 'manage_pricing',
    labelFr: 'Attribuer plafonds de crédit & délais de paiement',
    descriptionFr: 'Configuration des conditions commerciales spécifiques.',
    domain: 'CUSTOMERS_B2B',
  },

  // SUPPLIERS
  {
    code: 'suppliers.read',
    resource: 'suppliers',
    action: 'read',
    labelFr: 'Consulter le répertoire des fournisseurs',
    descriptionFr: 'Lecture des coordonnées usines, devises et délais.',
    domain: 'SUPPLIERS',
  },
  {
    code: 'suppliers.create',
    resource: 'suppliers',
    action: 'create',
    labelFr: 'Ajouter de nouveaux fournisseurs',
    descriptionFr: 'Création de fiches fournisseurs Chine/Dubaï/Local.',
    domain: 'SUPPLIERS',
  },
  {
    code: 'suppliers.update',
    resource: 'suppliers',
    action: 'update',
    labelFr: 'Modifier les fournisseurs & délais',
    descriptionFr: 'Mise à jour des coordonnées et devises de facturation.',
    domain: 'SUPPLIERS',
  },
  {
    code: 'suppliers.delete',
    resource: 'suppliers',
    action: 'delete',
    labelFr: 'Désactiver / Supprimer des fournisseurs',
    descriptionFr: 'Archivage de fournisseurs inactifs.',
    domain: 'SUPPLIERS',
  },

  // IMPORTS_EXPORTS
  {
    code: 'imports.read',
    resource: 'imports',
    action: 'read',
    labelFr: 'Consulter l’historique des imports & rapports',
    descriptionFr: 'Visualisation des sessions passées et téléchargement des logs.',
    domain: 'IMPORTS_EXPORTS',
  },
  {
    code: 'imports.create',
    resource: 'imports',
    action: 'create',
    labelFr: 'Téléverser et tester des imports (Dry-Run)',
    descriptionFr: 'Analyse de classeurs Excel/CSV et vérification des écarts.',
    domain: 'IMPORTS_EXPORTS',
  },
  {
    code: 'imports.apply',
    resource: 'imports',
    action: 'apply',
    labelFr: 'Appliquer les imports sur le catalogue',
    descriptionFr: 'Exécution définitive des modifications en masse.',
    domain: 'IMPORTS_EXPORTS',
  },
  {
    code: 'imports.cancel',
    resource: 'imports',
    action: 'cancel',
    labelFr: 'Annuler une session d’importation en attente',
    descriptionFr: 'Rejet d’un fichier non validé.',
    domain: 'IMPORTS_EXPORTS',
  },
  {
    code: 'products.export',
    resource: 'products',
    action: 'export',
    labelFr: 'Générer des exports de catalogue (CSV / XLSX)',
    descriptionFr: 'Extraction du catalogue avec masquage sécurisé selon les rôles.',
    domain: 'IMPORTS_EXPORTS',
  },

  // ADMIN_SECURITY
  {
    code: 'users.manage',
    resource: 'users',
    action: 'manage',
    labelFr: 'Gérer les comptes du staff (Création, Rôles, Suspension)',
    descriptionFr: 'Attribution des rôles et contrôle des accès administrateurs.',
    domain: 'ADMIN_SECURITY',
  },
  {
    code: 'audit.read',
    resource: 'audit',
    action: 'read',
    labelFr: 'Consulter le journal d’audit immuable',
    descriptionFr: 'Traçabilité complète des actions financières et système.',
    domain: 'ADMIN_SECURITY',
  },

  // CMS
  {
    code: 'cms.read',
    resource: 'cms',
    action: 'read',
    labelFr: 'Consulter les sections CMS & bannières vitrine',
    descriptionFr: 'Lecture de la structure des pages et contenus de la vitrine.',
    domain: 'CMS',
  },
  {
    code: 'cms.manage',
    resource: 'cms',
    action: 'manage',
    labelFr: 'Modifier les contenus vitrine & bannières d’accueil',
    descriptionFr: 'Édition, réordonnancement et activation des sections de la page d’accueil.',
    domain: 'CMS',
  },

  // NOTIFICATIONS
  {
    code: 'notifications.read',
    resource: 'notifications',
    action: 'read',
    labelFr: 'Consulter le centre de notifications & alertes',
    descriptionFr: 'Lecture des notifications du tableau de bord et événements système.',
    domain: 'NOTIFICATIONS',
  },
  {
    code: 'notifications.manage',
    resource: 'notifications',
    action: 'manage',
    labelFr: 'Gérer les passerelles & modèles de notification',
    descriptionFr: 'Édition des modèles SMS/WhatsApp et renvoi des alertes échouées.',
    domain: 'NOTIFICATIONS',
  },

  // ANALYTICS_REPORTS
  {
    code: 'analytics.read',
    resource: 'analytics',
    action: 'read',
    labelFr: 'Consulter les tableaux de bord analytiques',
    descriptionFr: 'Accès aux graphiques des ventes, entonnoir de conversion et indicateurs de performance.',
    domain: 'ANALYTICS_REPORTS',
  },
  {
    code: 'reports.read',
    resource: 'reports',
    action: 'read',
    labelFr: 'Consulter les rapports détaillés & métriques avancées',
    descriptionFr: 'Rapports de ventes par wilaya, rentabilité par marque et réconciliation COD.',
    domain: 'ANALYTICS_REPORTS',
  },
  {
    code: 'reports.export',
    resource: 'reports',
    action: 'export',
    labelFr: 'Exporter les rapports d’activité (CSV / XLSX)',
    descriptionFr: 'Téléchargement des données brutes agrégées selon les habilitations.',
    domain: 'ANALYTICS_REPORTS',
  },

  // SYSTEM_SETTINGS
  {
    code: 'settings.read',
    resource: 'settings',
    action: 'read',
    labelFr: 'Consulter les coordonnées & paramètres généraux',
    descriptionFr: 'Lecture des paramètres du site, réseaux sociaux et configurations.',
    domain: 'SYSTEM_SETTINGS',
  },
  {
    code: 'settings.manage',
    resource: 'settings',
    action: 'manage',
    labelFr: 'Modifier les paramètres généraux & coordonnées du site',
    descriptionFr: 'Mise à jour des téléphones, adresses, réseaux sociaux et SEO.',
    domain: 'SYSTEM_SETTINGS',
  },
];
